### ISSUE TITLE
OrderedDict Error in v0.6.0 

### ISSUE THREAD

**Issue by lstagner** [cmacmackin/markdown-include#25]
The recent release has broken my [documentation build](https://travis-ci.org/github/D3DEnergetic/FIDASIM/builds/720775160)

Here is the relevant error message.

```
/home/travis/build/D3DEnergetic/FIDASIM/docs/fidasim.md
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/ford", line 11, in <module>
    sys.exit(run())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/ford/__init__.py", line 385, in run
    proj_data, proj_docs, md = initialize()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/ford/__init__.py", line 141, in initialize
    extension_configs={'markdown_include.include': {'base_path': md_base}})
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/markdown/__init__.py", line 187, in registerExtensions
    ext.extendMarkdown(self, globals())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/markdown_include/include.py", line 58, in extendMarkdown
    md.preprocessors.register(IncludePreprocessor(md,self.getConfigs()), 'include', 101)
AttributeError: 'OrderedDict' object has no attribute 'register'
make: *** [docs] Error 1
```

**Comment by lstagner** [comment]
It seems the bug was introduced in PR #16

**Comment by pedrosousa** [comment]
You should upgrade your version of the Python-Markdown package to 3.1. This is the last version still compatible with Python 2.7 and that already provides the new API (namely the `register` function).

However, note that Python 2.7 reached end-of-life on 2020-01-01 and Python-Markdown 3.2 has dropped support for it. To be able to upgrade to Python-Markdown 3.2, you need to upgrade to Python 3.

**Comment by lstagner** [comment]
Your right. I have changed my build script to use Python 3 and the issue went away.
